name: Google Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Google Test Frmra
      # Build your program with the given configuration
      run: ls -l;
      
    - name: Build Google Test Frmra
      # Build your program with the given configuration
      run: echo ${{github.workspace}};

    - name: Build Project
      # Build your program with the given configuration
      run: info=$(python3 --version);echo "${info}"

    - name: Build Google Test
      # Build your program with the given configuration
      run: cd ${{github.workspace}};

    - name: Running
      # Build your program with the given configuration
      run: cd ${{github.workspace}};python -m unittest discover -s ./test -p 'test_*.py' --verbose
      
